export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
export const MY_WALLETS_UPDATE = 'MY_WALLETS_UPDATE';
export const WALLET_FAVOURITES_ADD = 'WALLET_FAVOURITES_ADD';
export const WALLET_FAVOURITES_REMOVE = 'WALLET_FAVOURITES_REMOVE';
export const WALLETS_CLEAR = 'WALLETS_CLEAR';

export const SET_WALLET_DATA = 'SET_TOTAL_INCOME';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_NEW_INCOME = 'FETCH_NEW_INCOME';
export const FETCH_NEW_EXPENSE = 'FETCH_NEW_EXPENSE';

export const ADD_NEW_INCOME_CATEGORY = 'ADD_NEW_INCOME_CATEGORY';
export const ADD_NEW_EXPENSE_CATEGORY = 'ADD_NEW_EXPENSE_CATEGORY';
export const INCOME_CATEGORIES_UPDATE = 'INCOME_CATEGORIES_UPDATE';
export const EXPENSE_CATEGORIES_UPDATE = 'EXPENSE_CATEGORIES_UPDATE';
export const INFO_ELEMENT_OPEN = 'SNACKBAR_OPEN'; 
export const INFO_ELEMENT_CLOSE = 'SNACKBAR_CLOSE';
export const INFO_DIALOG_OPEN = 'INFO_DIALOG_OPEN';
export const INFO_DIALOG_CLOSE = 'INFO_DIALOG_CLOSE';

export const SIGNUP = 'SIGNUP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
